[package]
name = "finaz"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "*", features = ["full"]}
serde = { version = "*", features = ["derive"] }
sqlx = {version = "*", features = ["migrate", "sqlite-unbundled", "runtime-tokio", "uuid", "chrono"]}